import Groq from "groq-sdk";
import config from "../config/config.js";

/**
 * Service to generate multiple-choice quiz questions using Groq AI.
 * @param {Object} params
 * @param {string} params.topic - Subject or topic description (e.g. "React Hooks")
 * @param {number} [params.count=5] - Number of questions to generate (1 to 10)
 * @param {string} [params.difficulty="medium"] - "easy" | "medium" | "hard"
 * @param {string} [params.additionalContext] - Optional extra instructions or guidelines
 * @returns {Promise<Array>} List of formatted questions
 */
export const generateAIQuestionsService = async ({
  topic,
  count = 5,
  difficulty = "medium",
  additionalContext = "",
}) => {
  const apiKey = config.groqApiKey;

  if (!apiKey) {
    const error = new Error("GROQ_API_KEY is not configured in backend environment.");
    error.statusCode = 500;
    throw error;
  }

  const groq = new Groq({ apiKey });

  const numQuestions = Math.min(Math.max(parseInt(count, 10) || 5, 1), 10);
  const targetDifficulty = ["easy", "medium", "hard"].includes(difficulty?.toLowerCase())
    ? difficulty.toLowerCase()
    : "medium";

  const systemPrompt = `You are an expert AI exam question generator for an online quiz platform.
Your task is to generate high-quality multiple choice questions (MCQs) on the given topic.

CRITICAL REQUIREMENTS:
1. Output MUST be valid, raw JSON only. Do not include markdown code blocks, backticks, or conversational text.
2. The JSON object MUST have a top-level key "questions" containing an array of question objects.
3. Each question object MUST contain:
   - "questionText": Clear, concise string asking the question.
   - "marks": Integer score for the question (default 5 for medium, 2 for easy, 10 for hard).
   - "difficulty": String ("easy", "medium", or "hard").
   - "options": An array of EXACTLY 4 option objects.
4. Each option object MUST contain:
   - "optionText": String content for the choice.
   - "isCorrect": Boolean (true or false).
5. EXACTLY ONE option per question MUST have "isCorrect": true, and the other 3 MUST have "isCorrect": false.`;

  const userPrompt = `Topic: "${topic}"
Number of questions: ${numQuestions}
Difficulty: ${targetDifficulty}
${additionalContext ? `Additional Instructions: ${additionalContext}` : ""}

Generate ${numQuestions} ${targetDifficulty} multiple-choice questions now in pure JSON.`;

  const completion = await groq.chat.completions.create({
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt },
    ],
    model: "llama-3.3-70b-versatile",
    temperature: 0.6,
    response_format: { type: "json_object" },
  });

  const responseContent = completion.choices[0]?.message?.content;

  if (!responseContent) {
    throw new Error("Empty response received from Groq AI service.");
  }

  let parsed;
  try {
    parsed = JSON.parse(responseContent);
  } catch (err) {
    console.error("Failed to parse Groq AI response:", responseContent);
    throw new Error("AI returned malformed JSON payload. Please try again.");
  }

  const rawQuestions = parsed.questions || parsed.data || (Array.isArray(parsed) ? parsed : []);

  if (!Array.isArray(rawQuestions) || rawQuestions.length === 0) {
    throw new Error("No questions were generated by the AI service.");
  }

  // Sanitize and validate options
  const sanitizedQuestions = rawQuestions.map((q, index) => {
    const rawOptions = Array.isArray(q.options) ? q.options : [];
    
    // Ensure exactly 4 options
    let formattedOptions = rawOptions.slice(0, 4).map((opt) => ({
      optionText: String(opt.optionText || opt.text || "").trim(),
      isCorrect: Boolean(opt.isCorrect),
    }));

    // If options count is less than 4, fill remaining
    while (formattedOptions.length < 4) {
      formattedOptions.push({
        optionText: `Option ${formattedOptions.length + 1}`,
        isCorrect: false,
      });
    }

    // Ensure exactly one is correct
    const correctCount = formattedOptions.filter((o) => o.isCorrect).length;
    if (correctCount !== 1) {
      formattedOptions = formattedOptions.map((opt, i) => ({
        ...opt,
        isCorrect: i === 0, // Fallback to first option if none/multiple marked
      }));
    }

    return {
      questionText: String(q.questionText || `Generated Question ${index + 1}`).trim(),
      marks: Number(q.marks) || (targetDifficulty === "easy" ? 2 : targetDifficulty === "hard" ? 10 : 5),
      difficulty: targetDifficulty,
      options: formattedOptions,
    };
  });

  return sanitizedQuestions;
};
