version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quimora_app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/quimora
      - JWT_SECRET=quimora_super_secret_production_key_2026
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: quimora_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
